import mongoose from 'mongoose';
const SuperAdminSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  //id is automatically generated by MongoDB
  SuperAdminId: mongoose.Schema.Types.ObjectId,
});
export const SuperAdmin = mongoose.model('SuperAdmin', SuperAdminSchema);


const AdminSchema = mongoose.Schema({
  firstname:{
    type: String,
    required: true,
  },
  lastname:{
    type: String,
    required: true,
  },
  phoneNo:{
    type: Number,
    required: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  collage: {
    type: String,
    required: true,
  },
  University: {
    type: String,
    required: true,
  },
  department: {
    type: String,
    required: true,
  },
  gender: {
    type: String,
    required: true,
  },
  Address:{
    type: String,
    required: true,
  },
  //id is automatically generated by MongoDB
  AdminId: mongoose.Schema.Types.ObjectId,
  });
  export const Admin = mongoose.model('Admin', AdminSchema);
  export default{Admin, SuperAdmin};